name: Test

on:
    push:
        branches: ['*']
    pull_request:
        branches: ['*']

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: NPM Install
              run: npm i

            - name: Unit tests
              run: npm run test:unit

            - name: Install Playwright
              run: npx playwright install

            - name: Integrations tests
              run: |
              export EMAIL_FROM="noreply@bluevire.com"
              export SMTP_SERVER_ADDRESS="mail.bluevire.com"
              export SMTP_SERVER_PORT="465"
              export SMTP_SERVER_USERNAME="noreply@bluevire.com"
              export SMTP_SERVER_PASSWORD="V@830%r0i]Ux"
              npm run test:integration
